export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_TVSERIES = "GET_LIST_TVSERIES";
export const GET_LIST_CARTOON = "GET_LIST_CARTOON";
export const DETAIL_MOVIE = "DETAIL_MOVIE";
export const DETAIL_TVSERIES = "DETAIL_TVSERIES";
export const DETAIL_CARTOON = "DETAIL_CARTOON";
export const LOGIN_USER = "LOGIN_USER";
export const ADD_TO_CART = "ADD_TO_CART";